//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megazone.SubtitleEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Megazone.SubtitleEditor.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ADD_CAPTION {
            get {
                return ResourceManager.GetString("CNT_ADD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ADD_NEW_CAPTION {
            get {
                return ResourceManager.GetString("CNT_ADD_NEW_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ADD_ROW {
            get {
                return ResourceManager.GetString("CNT_ADD_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add row above과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ADD_ROW_ABOVE {
            get {
                return ResourceManager.GetString("CNT_ADD_ROW_ABOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add row at last과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ADD_ROW_AT_LAST {
            get {
                return ResourceManager.GetString("CNT_ADD_ROW_AT_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add row below과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ADD_ROW_BELOW {
            get {
                return ResourceManager.GetString("CNT_ADD_ROW_BELOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust all time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ADJUST_ALL_TIME {
            get {
                return ResourceManager.GetString("CNT_ADJUST_ALL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adjust time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ADJUST_TIME {
            get {
                return ResourceManager.GetString("CNT_ADJUST_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All subtitle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ALL_CAPTIONS {
            get {
                return ResourceManager.GetString("CNT_ALL_CAPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ALL_FILES {
            get {
                return ResourceManager.GetString("CNT_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hyper Subtitle Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_APPLICATION_NAME {
            get {
                return ResourceManager.GetString("CNT_APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_APPLY {
            get {
                return ResourceManager.GetString("CNT_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_AUTO_LOGIN {
            get {
                return ResourceManager.GetString("CNT_AUTO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto adjust end times과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_AUTOADJUST_ENDTIMES {
            get {
                return ResourceManager.GetString("CNT_AUTOADJUST_ENDTIMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_BACKWARD {
            get {
                return ResourceManager.GetString("CNT_BACKWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_BOLD {
            get {
                return ResourceManager.GetString("CNT_BOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buffering time(second)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_BUFFERING_TIME {
            get {
                return ResourceManager.GetString("CNT_BUFFERING_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CANCEL {
            get {
                return ResourceManager.GetString("CNT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max length of subtitle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CAPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("CNT_CAPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min length of subtitle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CAPTION_MIN_LENGTH {
            get {
                return ResourceManager.GetString("CNT_CAPTION_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character/Second과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CHARS_PER_SECOND {
            get {
                return ResourceManager.GetString("CNT_CHARS_PER_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CLOSE {
            get {
                return ResourceManager.GetString("CNT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CONFIRM {
            get {
                return ResourceManager.GetString("CNT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contents과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CONTENTS {
            get {
                return ResourceManager.GetString("CNT_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just now과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CONVERTER_BEFORE {
            get {
                return ResourceManager.GetString("CNT_CONVERTER_BEFORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} hours ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CONVERTER_BEFORE_HOURS {
            get {
                return ResourceManager.GetString("CNT_CONVERTER_BEFORE_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} minutes ago과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CONVERTER_BEFORE_MINUTES {
            get {
                return ResourceManager.GetString("CNT_CONVERTER_BEFORE_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} / {1} {2:t}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CONVERTER_MMDD {
            get {
                return ResourceManager.GetString("CNT_CONVERTER_MMDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yesterday {0:t}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CONVERTER_YESTERDAY {
            get {
                return ResourceManager.GetString("CNT_CONVERTER_YESTERDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} / {2}, {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CONVERTER_YYYYMMDD {
            get {
                return ResourceManager.GetString("CNT_CONVERTER_YYYYMMDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_COPY {
            get {
                return ResourceManager.GetString("CNT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_COPY_CAPTION {
            get {
                return ResourceManager.GetString("CNT_COPY_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_COPY_ROW {
            get {
                return ResourceManager.GetString("CNT_COPY_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("CNT_COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CREATE_NEW_CAPTION {
            get {
                return ResourceManager.GetString("CNT_CREATE_NEW_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no condition that matches result.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CRITERIA_NOT_MATCH_RESULT {
            get {
                return ResourceManager.GetString("CNT_CRITERIA_NOT_MATCH_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut row(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_CUT_ROW {
            get {
                return ResourceManager.GetString("CNT_CUT_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_DELETE {
            get {
                return ResourceManager.GetString("CNT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete row(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_DELETE_ROWS {
            get {
                return ResourceManager.GetString("CNT_DELETE_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deploy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_DEPLOY {
            get {
                return ResourceManager.GetString("CNT_DEPLOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download excel forms과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_DOWNLOAD_EXCEL_TEMPLET {
            get {
                return ResourceManager.GetString("CNT_DOWNLOAD_EXCEL_TEMPLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_DURATION {
            get {
                return ResourceManager.GetString("CNT_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_EDIT {
            get {
                return ResourceManager.GetString("CNT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit track info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_EDIT_CAPTION_INFO {
            get {
                return ResourceManager.GetString("CNT_EDIT_CAPTION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_END_TIME {
            get {
                return ResourceManager.GetString("CNT_END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ERROR {
            get {
                return ResourceManager.GetString("CNT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_EXIT {
            get {
                return ResourceManager.GetString("CNT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_EXPORT {
            get {
                return ResourceManager.GetString("CNT_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export all to WebVtt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_EXPORT_ALL_WEBVTT {
            get {
                return ResourceManager.GetString("CNT_EXPORT_ALL_WEBVTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export to Excel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_EXPORT_EXCEL {
            get {
                return ResourceManager.GetString("CNT_EXPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export to Project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_EXPORT_PROJECT {
            get {
                return ResourceManager.GetString("CNT_EXPORT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export to WebVtt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_EXPORT_WEBVTT {
            get {
                return ResourceManager.GetString("CNT_EXPORT_WEBVTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_FILE {
            get {
                return ResourceManager.GetString("CNT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_FIND {
            get {
                return ResourceManager.GetString("CNT_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_FIND_ALL {
            get {
                return ResourceManager.GetString("CNT_FIND_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find contents과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_FIND_CONTENTS {
            get {
                return ResourceManager.GetString("CNT_FIND_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_FIND_FILE {
            get {
                return ResourceManager.GetString("CNT_FIND_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_FIND_NEXT {
            get {
                return ResourceManager.GetString("CNT_FIND_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_FORWARD {
            get {
                return ResourceManager.GetString("CNT_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to subtitle number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_GO_TO_CAPTION_NUMBER {
            get {
                return ResourceManager.GetString("CNT_GO_TO_CAPTION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_GO_TO_NUMBER {
            get {
                return ResourceManager.GetString("CNT_GO_TO_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Word match과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_HOW_MANY_MATCH {
            get {
                return ResourceManager.GetString("CNT_HOW_MANY_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hyper Subtitle Editor Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_HYPER_SUBTITLE_EDITOR_INFO {
            get {
                return ResourceManager.GetString("CNT_HYPER_SUBTITLE_EDITOR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_IMPORT {
            get {
                return ResourceManager.GetString("CNT_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import excel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_IMPORT_EXCEL {
            get {
                return ResourceManager.GetString("CNT_IMPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_IMPORT_PROJECT {
            get {
                return ResourceManager.GetString("CNT_IMPORT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_INFO {
            get {
                return ResourceManager.GetString("CNT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse file or enter URL to import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_INPUT_VIDEO_PATH {
            get {
                return ResourceManager.GetString("CNT_INPUT_VIDEO_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert into a next position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_INSERT_AFTER {
            get {
                return ResourceManager.GetString("CNT_INSERT_AFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert into a current position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_INSERT_AT_CURRENT_POSITION {
            get {
                return ResourceManager.GetString("CNT_INSERT_AT_CURRENT_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert into a previous position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_INSERT_BEFORE {
            get {
                return ResourceManager.GetString("CNT_INSERT_BEFORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_ITALIC {
            get {
                return ResourceManager.GetString("CNT_ITALIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JOB ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_JOB_ID {
            get {
                return ResourceManager.GetString("CNT_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_KIND {
            get {
                return ResourceManager.GetString("CNT_KIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_LANGUAGE {
            get {
                return ResourceManager.GetString("CNT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load all tracks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_LOAD_ALL_CAPTIONS {
            get {
                return ResourceManager.GetString("CNT_LOAD_ALL_CAPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_LOAD_CAPTION {
            get {
                return ResourceManager.GetString("CNT_LOAD_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_LOG_OUT {
            get {
                return ResourceManager.GetString("CNT_LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max length per row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_MAX_LENGTH_PER_ROW {
            get {
                return ResourceManager.GetString("CNT_MAX_LENGTH_PER_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max row number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_MAX_ROW_COUNT {
            get {
                return ResourceManager.GetString("CNT_MAX_ROW_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max character per second과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_MAX_TEXT_COUNT_PER_SECOND {
            get {
                return ResourceManager.GetString("CNT_MAX_TEXT_COUNT_PER_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute : Second : Millisecond과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_MINUTE_SECOND_MILLISECOND {
            get {
                return ResourceManager.GetString("CNT_MINUTE_SECOND_MILLISECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_MOVE {
            get {
                return ResourceManager.GetString("CNT_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_NAME {
            get {
                return ResourceManager.GetString("CNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEXT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_NEXT {
            get {
                return ResourceManager.GetString("CNT_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_NEXT_PAGE {
            get {
                return ResourceManager.GetString("CNT_NEXT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("CNT_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path does not exist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_NOT_EXIST_PATH {
            get {
                return ResourceManager.GetString("CNT_NOT_EXIST_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_OPEN {
            get {
                return ResourceManager.GetString("CNT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open track file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_OPEN_CAPTION_FILE {
            get {
                return ResourceManager.GetString("CNT_OPEN_CAPTION_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open from MCM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_OPEN_FROM_MCM {
            get {
                return ResourceManager.GetString("CNT_OPEN_FROM_MCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open from job과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_OPEN_IN_JOB {
            get {
                return ResourceManager.GetString("CNT_OPEN_IN_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_OPEN_URL {
            get {
                return ResourceManager.GetString("CNT_OPEN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open video과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_OPEN_VIDEO {
            get {
                return ResourceManager.GetString("CNT_OPEN_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as file path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_OPEN_WITH_FILE_ADDRESS {
            get {
                return ResourceManager.GetString("CNT_OPEN_WITH_FILE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste row(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PASTE_ROW {
            get {
                return ResourceManager.GetString("CNT_PASTE_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play/Pause과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PLAY_AND_PAUSE_VIDEO {
            get {
                return ResourceManager.GetString("CNT_PLAY_AND_PAUSE_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Backward by 0.5 sec과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PLAY_BACKWARD_BY_HALF_SEC {
            get {
                return ResourceManager.GetString("CNT_PLAY_BACKWARD_BY_HALF_SEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Forward by 0.5 sec과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PLAY_FORWARD_BY_HALF_SEC {
            get {
                return ResourceManager.GetString("CNT_PLAY_FORWARD_BY_HALF_SEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PREV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PREVIOUS {
            get {
                return ResourceManager.GetString("CNT_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PREVIOUS_PAGE {
            get {
                return ResourceManager.GetString("CNT_PREVIOUS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PROGRAM_INFO {
            get {
                return ResourceManager.GetString("CNT_PROGRAM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PROGRAM_SETTING {
            get {
                return ResourceManager.GetString("CNT_PROGRAM_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PROJECT_START {
            get {
                return ResourceManager.GetString("CNT_PROJECT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_PUBLISH {
            get {
                return ResourceManager.GetString("CNT_PUBLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_REFRESH {
            get {
                return ResourceManager.GetString("CNT_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete subtitle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_REMOVE_CAPTION {
            get {
                return ResourceManager.GetString("CNT_REMOVE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete font style과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_REMOVE_TEXT_FORMATTING {
            get {
                return ResourceManager.GetString("CNT_REMOVE_TEXT_FORMATTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_REPLACE {
            get {
                return ResourceManager.GetString("CNT_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_REPLACE_ALL {
            get {
                return ResourceManager.GetString("CNT_REPLACE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace with과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_REPLACE_CONTENTS {
            get {
                return ResourceManager.GetString("CNT_REPLACE_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_RESET {
            get {
                return ResourceManager.GetString("CNT_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SAVE {
            get {
                return ResourceManager.GetString("CNT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SEARCH {
            get {
                return ResourceManager.GetString("CNT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all rows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECT_ALL_ROWS {
            get {
                return ResourceManager.GetString("CNT_SELECT_ALL_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select previous rows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECT_BEFORE_ROW {
            get {
                return ResourceManager.GetString("CNT_SELECT_BEFORE_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a track file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECT_CAPTION_FILE {
            get {
                return ResourceManager.GetString("CNT_SELECT_CAPTION_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select subtitle that you want copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECT_CAPTION_TO_COPY {
            get {
                return ResourceManager.GetString("CNT_SELECT_CAPTION_TO_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select subtitle file that is in excel format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECT_EXCEL_CAPTION_FILE {
            get {
                return ResourceManager.GetString("CNT_SELECT_EXCEL_CAPTION_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select job과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECT_JOB {
            get {
                return ResourceManager.GetString("CNT_SELECT_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select next row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECT_NEXT_ROW {
            get {
                return ResourceManager.GetString("CNT_SELECT_NEXT_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select video과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECT_VIDEO {
            get {
                return ResourceManager.GetString("CNT_SELECT_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only selected subtitle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECTED_CAPTION {
            get {
                return ResourceManager.GetString("CNT_SELECTED_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only selected subtitle and rest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SELECTED_CAPTION_AND_ALL_AFTER {
            get {
                return ResourceManager.GetString("CNT_SELECTED_CAPTION_AND_ALL_AFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set end time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SET_END_TIME {
            get {
                return ResourceManager.GetString("CNT_SET_END_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set start time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SET_START_TIME {
            get {
                return ResourceManager.GetString("CNT_SET_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SETTING {
            get {
                return ResourceManager.GetString("CNT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtitle settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SETTING_CAPTION {
            get {
                return ResourceManager.GetString("CNT_SETTING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SETTING_LOGIN {
            get {
                return ResourceManager.GetString("CNT_SETTING_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video player settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SETTING_VIDEO_PLAYER {
            get {
                return ResourceManager.GetString("CNT_SETTING_VIDEO_PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SHEET {
            get {
                return ResourceManager.GetString("CNT_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single line length과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SINGLE_LINE_LENGTH {
            get {
                return ResourceManager.GetString("CNT_SINGLE_LINE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Space between subtitle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_SPACE_BETWEEN_CAPTIONS {
            get {
                return ResourceManager.GetString("CNT_SPACE_BETWEEN_CAPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_START_TIME {
            get {
                return ResourceManager.GetString("CNT_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time adjustment unit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_TIME_ADJUSTMENT_UNIT {
            get {
                return ResourceManager.GetString("CNT_TIME_ADJUSTMENT_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_TOOL {
            get {
                return ResourceManager.GetString("CNT_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total length과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_TOTAL_LENGTH {
            get {
                return ResourceManager.GetString("CNT_TOTAL_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underline과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_UNDERLINE {
            get {
                return ResourceManager.GetString("CNT_UNDERLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_VIDEO {
            get {
                return ResourceManager.GetString("CNT_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View log folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_VIEW_LOG_FOLDERE {
            get {
                return ResourceManager.GetString("CNT_VIEW_LOG_FOLDERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_WAITING {
            get {
                return ResourceManager.GetString("CNT_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CNT_WARNING {
            get {
                return ResourceManager.GetString("CNT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please try again after checking elastic transcoder authorization.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_CONFIRM_ELASTIC_TRANSCODER_AUTHORITY {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_ELASTIC_TRANSCODER_AUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deploy failed. Please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_DEPLOY_FAIL {
            get {
                return ResourceManager.GetString("MSG_DEPLOY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully deployed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_DEPLOY_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DEPLOY_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No registered tracks.
        ///You can add one by dragging a file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_DRAG_OPEN_CAPTION {
            get {
                return ResourceManager.GetString("MSG_DRAG_OPEN_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No video.
        ///You can load one by dragging a file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_DRAG_OPEN_VIDEO {
            get {
                return ResourceManager.GetString("MSG_DRAG_OPEN_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate subtitle with next one.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_DUPLICATE_TO_THE_NEXT_CAPTION {
            get {
                return ResourceManager.GetString("MSG_DUPLICATE_TO_THE_NEXT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate subtitle with previous one.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_DUPLICATE_TO_THE_PREVIOUS_CAPTION {
            get {
                return ResourceManager.GetString("MSG_DUPLICATE_TO_THE_PREVIOUS_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred during play.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_ERROR_TRYING_TO_PLAY {
            get {
                return ResourceManager.GetString("MSG_ERROR_TRYING_TO_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create excel file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_EXPORT_EXCEL_FILE_FAIL {
            get {
                return ResourceManager.GetString("MSG_EXPORT_EXCEL_FILE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a row number that you are going to move.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_INPUT_MOVE_ROW_NUMBER {
            get {
                return ResourceManager.GetString("MSG_INPUT_MOVE_ROW_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation required to execute application is incorrect.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_INVALID_APPLICATION_INFO {
            get {
                return ResourceManager.GetString("MSG_INVALID_APPLICATION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job id {0} has been copied to clipboard.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_JOB_ID_COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("MSG_JOB_ID_COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep the current tab?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_KEEP_CURRENT_TAB {
            get {
                return ResourceManager.GetString("MSG_KEEP_CURRENT_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - Hyper Subtitle Editor is using FFmpeg.exe for extracting thumbnail images and media metadata under the LGPLv2.1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_LICENSE_FFMPEG {
            get {
                return ResourceManager.GetString("MSG_LICENSE_FFMPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - Hyper Subtitle Editor is using naudio for Video Player under the Ms-PL licnese과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_LICENSE_NAUDIO {
            get {
                return ResourceManager.GetString("MSG_LICENSE_NAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have a file that you are working on.
        ///Are you going to load a project?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_LOAD_GROUP_FILE {
            get {
                return ResourceManager.GetString("MSG_LOAD_GROUP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No subtitle selected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_NO_CAPTION_SELECTED {
            get {
                return ResourceManager.GetString("MSG_NO_CAPTION_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No displayable contents.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_NO_PRINTABLE_CONTENTS {
            get {
                return ResourceManager.GetString("MSG_NO_PRINTABLE_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}&apos;s path has been copied to clipboard.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_PATH_COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("MSG_PATH_COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred during save.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_SAVE_FAIL {
            get {
                return ResourceManager.GetString("MSG_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Videos playback status can vary with user&apos;s network condition or pc environment.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MSG_VIDEO_PLAY_CONDITION {
            get {
                return ResourceManager.GetString("MSG_VIDEO_PLAY_CONDITION", resourceCulture);
            }
        }
    }
}
